# Generated by Django 3.2.4 on 2021-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlshortadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=500)),
                ('shortend_url', models.CharField(max_length=500)),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
    ]
